import numpy as np

import torch
from torch import optim
from tensorboardX import SummaryWriter
torch.manual_seed(0)

import models
import utils
import data

import os
import sys

def _load_external_features(dataset, feat_pt_path, dataset_name):
    """
    Replace dataset.x with a pre-computed external feature tensor loaded from
    a .pt file.  Accepts:
      - a dict with key "x"  (schema written by preprocess_sbert_features.py)
      - a raw torch.Tensor   (fallback)

    Validation before replacement:
      1. shape[0] == dataset.num_nodes  (node-count alignment)
      2. dtype is floating-point        (cast to float32 if needed)
      3. no NaN or Inf values

    Returns the same dataset object with data.x replaced in-place.
    The input_size for the first GNN layer (derived from data.x.shape[1]
    immediately after this call in ModelTrainer._init) is updated automatically.

    Do NOT copy the weights_only=False kwarg into training code blindly 鈥?    it is used here because the .pt files are generated by our own trusted
    preprocessing pipeline and contain non-tensor metadata.
    """
    print(f"  [feat_pt] Loading external features: {feat_pt_path!r}")
    obj = torch.load(feat_pt_path, weights_only=False)

    if isinstance(obj, dict):
        if "x" not in obj:
            raise KeyError(
                f"feat_pt file is a dict but has no 'x' key.  "
                f"Available keys: {list(obj.keys())}"
            )
        x_ext = obj["x"]
        print(f"  [feat_pt] dict schema 鈥?encoder={obj.get('encoder', '?')}, "
              f"dim={obj.get('dim', '?')}, created_at={obj.get('created_at', '?')}")
    elif isinstance(obj, torch.Tensor):
        x_ext = obj
    else:
        raise TypeError(
            f"feat_pt must contain a dict or Tensor, got {type(obj).__name__}"
        )

    # Validation 1: node-count alignment
    expected_nodes = dataset.num_nodes
    if x_ext.shape[0] != expected_nodes:
        raise ValueError(
            f"feat_pt node count mismatch: file has {x_ext.shape[0]:,} rows, "
            f"dataset '{dataset_name}' has {expected_nodes:,} nodes."
        )

    # Validation 2: dtype 鈥?must be floating; cast to float32 if needed
    if not x_ext.is_floating_point():
        raise TypeError(
            f"feat_pt tensor must be floating-point, got {x_ext.dtype}"
        )
    if x_ext.dtype != torch.float32:
        print(f"  [feat_pt] casting {x_ext.dtype} 鈫?float32")
        x_ext = x_ext.float()

    # Validation 3: finite check
    if torch.isnan(x_ext).any():
        raise ValueError("feat_pt tensor contains NaN values.")
    if torch.isinf(x_ext).any():
        raise ValueError("feat_pt tensor contains Inf values.")

    orig_shape = tuple(dataset.x.shape) if dataset.x is not None else None
    print(
        f"  [feat_pt] Replacing data.x for '{dataset_name}': "
        f"original shape={orig_shape} 鈫?"
        f"new shape={tuple(x_ext.shape)}, dtype={x_ext.dtype}"
    )
    dataset.x = x_ext
    return dataset


class ModelTrainer:

    def __init__(self, args):
        self._args = args
        self._init()
        self.writer = SummaryWriter(log_dir="runs/BGRL_dataset({})".format(args.name))

    def _init(self):
        args = self._args
        os.environ["CUDA_VISIBLE_DEVICES"] = str(args.device)
        if args.device == -1:
            self._device = "cpu"
        else:
            self._device = f'cuda:{args.device}' if torch.cuda.is_available() else "cpu"
        self._dataset = data.Dataset(root=args.root, name=args.name)[0]
        print(f"Data: {self._dataset}")

        # Optional external feature replacement (--feat-pt).
        # Must happen BEFORE layers[] is built so input_size reflects the
        # new feature dimension (e.g. 768 for SBERT) rather than the original.
        if getattr(args, "feat_pt", None) is not None:
            self._dataset = _load_external_features(
                self._dataset, args.feat_pt, args.name
            )

        hidden_layers = [int(l) for l in args.layers]
        layers = [self._dataset.x.shape[1]] + hidden_layers
        self._model = models.BGRL(layer_config=layers, pred_hid=args.pred_hid, dropout=args.dropout, epochs=args.epochs).to(self._device)
        print(self._model)

        self._optimizer = optim.AdamW(params=self._model.parameters(), lr=args.lr, weight_decay= 1e-5)
        # learning rate
        scheduler = lambda epoch: epoch / 1000 if epoch < 1000 \
                    else ( 1 + np.cos((epoch-1000) * np.pi / (self._args.epochs - 1000))) * 0.5
        self._scheduler = optim.lr_scheduler.LambdaLR(self._optimizer, lr_lambda = scheduler)

    def _skip_eval(self) -> bool:
        """Return True when training-time node evaluation is intentionally disabled."""
        return self._args.name.lower() == "wn18rr" or getattr(self._args, "skip_eval", False)

    def _skip_eval_message(self) -> str:
        if self._args.name.lower() == "wn18rr":
            return "[{}] Evaluation skipped - not a node-classification dataset.".format(self._args.name)
        return "[{}] Evaluation skipped (--skip-eval).".format(self._args.name)

    def train(self):
        # get initial test results
        print("start training!")
        print("Initial Evaluation...")
        if self._skip_eval():
            print(self._skip_eval_message())
            dev_best = dev_std_best = test_best = test_std_best = float("nan")
        else:
            self.infer_embeddings()
            dev_best, dev_std_best, test_best, test_std_best = self.evaluate()
            self.writer.add_scalar("accs/val_acc", dev_best, 0)
            self.writer.add_scalar("accs/test_acc", test_best, 0)
            print("validation: {:.4f}, test: {:.4f}".format(dev_best, test_best))

        # start training
        self._model.train()
        for epoch in range(self._args.epochs):
            
            self._dataset.to(self._device)

            augmentation = utils.Augmentation(float(self._args.aug_params[0]),float(self._args.aug_params[1]),float(self._args.aug_params[2]),float(self._args.aug_params[3]))
            view1, view2 = augmentation._feature_masking(self._dataset, self._device)

            v1_output, v2_output, loss = self._model(
                x1=view1.x, x2=view2.x, edge_index_v1=view1.edge_index, edge_index_v2=view2.edge_index,
                edge_weight_v1=view1.edge_attr, edge_weight_v2=view2.edge_attr)
                
            self._optimizer.zero_grad()
            loss.backward()
            self._optimizer.step()
            self._scheduler.step()
            self._model.update_moving_average()
            sys.stdout.write('\rEpoch {}/{}, loss {:.4f}, lr {}'.format(epoch + 1, self._args.epochs, loss.data, self._optimizer.param_groups[0]['lr']))
            sys.stdout.flush()
            
            if (epoch + 1) % self._args.cache_step == 0:
                print("")
                print("\nEvaluating {}th epoch..".format(epoch + 1))
                if self._skip_eval():
                    print(self._skip_eval_message())
                else:
                    self.infer_embeddings()
                    dev_acc, dev_std, test_acc, test_std = self.evaluate()

                    if dev_best < dev_acc:
                        dev_best = dev_acc
                        dev_std_best = dev_std
                        test_best = test_acc
                        test_std_best = test_std

                    self.writer.add_scalar("stats/learning_rate", self._optimizer.param_groups[0]["lr"] , epoch + 1)
                    self.writer.add_scalar("accs/val_acc", dev_acc, epoch + 1)
                    self.writer.add_scalar("accs/test_acc", test_acc, epoch + 1)
                    print("validation: {:.4f}, test: {:.4f} \n".format(dev_acc, test_acc))
                
        
        f = open("BGRL_dataset({})_node.txt".format(self._args.name), "a")
        f.write("best valid acc : {} best valid std : {} best test acc : {} best test std : {} \n".format(dev_best, dev_std_best, test_best, test_std_best))
        f.close()

        print()
        print("[best] best_valid_acc={} best_valid_std={} best_test_acc={} best_test_std={}".format(dev_best, dev_std_best, test_best, test_std_best))
        print("Training Done!")
        

    def infer_embeddings(self):
        
        self._model.train(False)
        self._embeddings = self._labels = None

        self._dataset.to(self._device)
        v1_output, v2_output, _ = self._model(
            x1=self._dataset.x, x2=self._dataset.x,
            edge_index_v1=self._dataset.edge_index,
            edge_index_v2=self._dataset.edge_index,
            edge_weight_v1=self._dataset.edge_attr,
            edge_weight_v2=self._dataset.edge_attr)
        emb = v1_output.detach()
        y = self._dataset.y.detach()
        if self._embeddings is None:
            self._embeddings, self._labels = emb, y
        else:
            self._embeddings = torch.cat([self._embeddings, emb])
            self._labels = torch.cat([self._labels, y])
                
    
    def evaluate(self):
        """
        Used for producing the results of Experiment 3.2 in the BGRL paper. 
        """
        emb_dim, num_class = self._embeddings.shape[1], self._labels.unique().shape[0]
    
        dev_accs, test_accs = [], []
        
        for i in range(20):

            self._train_mask = self._dataset.train_mask[i]
            self._dev_mask = self._dataset.val_mask[i]
            if self._args.name == "WikiCS":
                self._test_mask = self._dataset.test_mask
            else :
                self._test_mask = self._dataset.test_mask[i]

            classifier = models.LogisticRegression(emb_dim, num_class).to(self._device)
            optimizer = torch.optim.Adam(classifier.parameters(), lr=0.01, weight_decay=0.0)

            for epoch in range(100):
                classifier.train()
                logits, loss = classifier(self._embeddings[self._train_mask], self._labels[self._train_mask])
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
            
            dev_logits, _ = classifier(self._embeddings[self._dev_mask], self._labels[self._dev_mask])
            test_logits, _ = classifier(self._embeddings[self._test_mask], self._labels[self._test_mask])
            dev_preds = torch.argmax(dev_logits, dim=1)
            test_preds = torch.argmax(test_logits, dim=1)
                    
            dev_acc = (torch.sum(dev_preds == self._labels[self._dev_mask]).float() / self._labels[self._dev_mask].shape[0]).detach().cpu().numpy()
            test_acc = (torch.sum(test_preds == self._labels[self._test_mask]).float() / self._labels[self._test_mask].shape[0]).detach().cpu().numpy()

            dev_accs.append(dev_acc * 100)
            test_accs.append(test_acc * 100)
                
        dev_accs = np.stack(dev_accs)
        test_accs = np.stack(test_accs)

        dev_acc, dev_std = dev_accs.mean(), dev_accs.std()
        test_acc, test_std = test_accs.mean(), test_accs.std()

        return dev_acc, dev_std, test_acc, test_std


def train_eval(args):
    trainer = ModelTrainer(args)
    trainer.train()
    trainer.writer.close()

    # Export encoder-only checkpoint for eval/run_lp.py (Layer 2 contract).
    if getattr(args, "export_encoder_ckpt", None) is not None:
        from pathlib import Path as _Path

        _repo_root = str(_Path(__file__).resolve().parents[2])
        if _repo_root not in sys.path:
            sys.path.insert(0, _repo_root)
        from eval.checkpoint import export_encoder_checkpoint

        _enc_sd = trainer._model.student_encoder.state_dict()
        _hidden = int(args.layers[-1])
        _input_dim = int(trainer._dataset.x.shape[1])
        _dataset_name = utils.decide_config(root=args.root, name=args.name)["name"]
        export_encoder_checkpoint(
            _enc_sd,
            args.export_encoder_ckpt,
            model_name="bgrl",
            dataset=_dataset_name,
            task_type="node",
            hidden_dim=_hidden,
            encoder_input_dim=_input_dim,
            backend="pyg",
            extra_metadata={"feat_pt_used": getattr(args, "feat_pt", None) is not None},
        )


def main():
    args = utils.parse_args()
    train_eval(args)


if __name__ == "__main__":
    main()
